name: sample-environment # the name of the environment
channels: # I recommend keeping this order
  - conda-forge
  - r
  - defaults
dependencies:
  - r-base # base r
  - r-essentials # You will probably want this
  - r-ggplot2 # required for analyses and plots
  - r-ggpmisc # required for analyses and plots
  - r-gridextra # required for analyses and plots